# Site settings
title: "Serverless Camp Tank Wars"
description: "Learn how to develop serverless cloud functions by participating in cloud tank warfare"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tankwars.serverless.camp" # the base hostname & protocol for your site
github_username: serverlesscamp 
# Build settings
markdown: kramdown
exclude: ['*.sh', 'template']
scripts: ['compiled.js'] # ['scripts/tw.js', 'scripts/promising-xhr.js', 'scripts/mini-emit.js', 'scripts/tankwars-client-api.js', 'scripts/tankwars-model.js', 'scripts/site.js']
social_header: "/assets/camp.png"
s3_bucket: tankwars.serverless.camp
cloudfront_dist: E1D2P34CXUH940
